config/routes.rb
Score::Application.routes.draw do
  resources :players

  root 'players#top_3'

  

end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
		@players = Player.all.order('score DESC')
	end

	def top_3
		@players = Player.all.order('score DESC').limit(3)
		render :index
	end

	def new
		@player = Player.new
	end
	
	def create
		@player = Player.new(player_params)
    	if @player.save
      		@players = Player.all.order('score DESC').limit(3)
     		render "index"
    	else
    		render "new"
   	 end
	end
	
	def update										
		player = Player.find(params[:id])
		score = player_params[:score].to_i + player.score.to_i
		player.update_attributes(score: score)
		@players = Player.all.order('score DESC').limit(3)
		score = 0
     		render "index"

	end
	def destroy
  		player = Player.find(params[:id])
  		player.destroy
 
  		@players = Player.all.order('score DESC').limit(3)
  		render "index"
end
	private
	def player_params
		params.require(:player).permit(:name, :score)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Score</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/index.html.erb
<section id="container">
<h1>Hey look, this is index</h1>
	<p id="new-player"><%= link_to "New Player", new_player_url %></p>

	<% @players.each do |player| %>
	<div class="player">
		<p> Name: <%= player.name.titleize %>, Score: <%= player.score %></p>

	<%= form_for player do |f| %>
		<%= f.label :score %>:
	  	<%= f.text_field :score, :class => 'score', :value => '0'%> 
	  	<%= f.hidden_field :id %>
	  	<%= f.submit %>
	<% end %>

	<%= link_to 'Destroy', player,
	                    method: :delete, data: { confirm: 'Are you sure?' } %>
		</div>
	<% end %>	
</section>

app/views/players/new.html.erb
<h1>Add a new player</h1>
<%#= @player.inspect %>

<%= form_for @player, url: {action: "create"} do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />


  <%= f.submit %>
<% end %>